dist: trusty

language: go

go:
  - 1.9

before_install:
  - sudo add-apt-repository ppa:masterminds/glide && sudo apt-get update
  - sudo apt-get install glide -y

branches:
  only:
    - master

script:
  - make